server:
  address: ":"
  port: 9690

# https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html
aws:
#  credentials:
#    aws_access_key_id: ""
#    aws_secret_access_key: ""
#    aws_region: ""
#    aws_profile: ""
#    aws_role_arn: ""
#    aws_web_identity_token_file: ""
  MetricDataQueries:
    - Id: m1
      MetricStat:
        Metric:
          Namespace: AWS/EC2
          MetricName: CPUUtilization
          Dimensions:
            - Name: AutoScalingGroupName
              Value: eks-prod-01-apps-01-aeg
        Period: 300
        Stat: Average
        Unit: Bytes
    - Id: m2
      MetricStat:
        Metric:
          Namespace: AWS/EC2
          MetricName: NetworkOut
          Dimensions:
            - Name: AutoScalingGroupName
              Value: eks-prod-01-apps-01-aeg
        Period: 300
        Stat: SampleCount
        Unit: Count
    - Id: m3
      MetricStat:
        Metric:
          Namespace: AWS/ELB
          MetricName: HealthyHostCount
          Dimensions:
            - Name: LoadBalancerName
              Value: my-lb-B
        Period: 300
        Stat: Sum
        Unit: None
