name: Build Test

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:

  prepare_tools:
    name: Prepare the Tools
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install promu
        run: make promu

      - name: Upload root
        uses: actions/upload-artifact@v1
        with:
          name: root
          path: .

  test:
    name: Test
    needs: prepare_tools
    runs-on: ubuntu-latest
    steps:
      - name: Download root
        uses: actions/download-artifact@v1
        with:
          name: root

      - name: Build and Test
        run: make

      - name: Check code modifications
        run: git diff --exit-code

      - name: Remove artifacts
        run: rm -v aws_cloudwatch_exporter
