name: Build Test Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  DOCKER_HUB_REPO: docker.io/slashdevops

jobs:

  prepare_tools:
    name: Prepare the Tools
    runs-on: ubuntu-latest
      steps:
        - name: Set up Go 1.x
          uses: actions/setup-go@v2
          with:
            go-version: ^1.14
          id: go

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Install promu
          run: make promu

  test:
    name: Test
    needs: prepare_tools
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        run: make

      - name: Check code modifications
        run: git diff --exit-code

      - name: Remove artifacts
        run: rm -v aws_cloudwatch_exporter

  build:
    name: Build
    needs: prepare_tools
    runs-on: ubuntu-latest
    steps:
      - name: Build Cross-Platform
        run: promu crossbuild -v

      - name: Upload .build folder
        uses: actions/upload-artifact@v1
        with:
          name: dot-build-dir
          path: .build

      - name: Copy .build/ into build/
          run: cp -rv .build build
          shell: bash

      - name: Build Docker Images
        run: make docker DOCKER_REPO=docker.io/slashdevops

      - name: Docker Tag Images Latest
        run: make docker-tag-latest DOCKER_REPO=docker.io/slashdevops

      - name: Show Docker Images
        run: docker images

  publish_docker_images:
    name: Publish Docker Images to Registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Show Docker Images
        run: docker images

      - name: Loging in Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish images in Docker Hub
        run: make docker-publish DOCKER_REPO=$DOCKER_HUB_REPO

      - name: Publish manifest in Docker Hub
        run: make docker-manifest DOCKER_REPO=$DOCKER_HUB_REPO


