name: Master branch workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  DOCKER_HUB_REPO: docker.io/slashdevops

jobs:

  build:
    name: Build Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install promu
        run: make promu

      - name: Build and Test Linux Platform Only
        run: make

      - name: Check code modifications
        run: git diff --exit-code

      - name: Build Cross-Platform
        run: promu crossbuild -v

      - name: Build Docker Images
        run: make docker DOCKER_REPO=docker.io/slashdevops

      - name: Docker Tag Images Latest
        run: make docker-tag-latest DOCKER_REPO=docker.io/slashdevops

      - name: Show Docker Images
        run: docker images

      - name: Show Docker Images
        run: docker images

      - name: Loging in Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish images in Docker Hub
        run: make docker-publish DOCKER_REPO=$DOCKER_HUB_REPO

      - name: Publish manifest in Docker Hub
        run: make docker-manifest DOCKER_REPO=$DOCKER_HUB_REPO


