name: Build, Test and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install promu
      run: make promu

    - name: Build Cross-Platform
      run: promu crossbuild -v

    - name: Build Docker Images
      run: make docker DOCKER_REPO=docker.io/slashdevops

    - name: Show Docker Images
      run: docker images